vim.keymap.set('n', '<Leader>e', '<cmd>!npx eslint %<cr>')
vim.keymap.set('n', '<Leader>s', '<cmd>!npx stylelint %<cr>')
vim.keymap.set('n', '<Leader>gp', '<cmd>Git push -f<cr>')
vim.keymap.set('n', '<Leader>gn', git_push_new_branch)
vim.keymap.set('n', '<Leader>t', run_test_or_last)
vim.keymap.set('n', 'sj', toggle_between_test_and_source_file, { silent = true })
